### PR TITLE
Use correct grant type

### PR DESCRIPTION
**Pull request by orbex**

### CODE REVIEW

**Comment by kahovskaia** [comment]
Thank you so much.
p. with disgusting api documentation

**Comment by sirian** [comment]
@kahovskaia this package no actively maintained since I left Admitad GmbH. There was `new` branch (totally rewritten) 
https://github.com/admitad/admitad-php-api/tree/new/src
Maybe it will be more suitable. 
@bulychev check PR or ping smbd from team)

**Comment by kahovskaia** [comment]
> @kahovskaia this package no actively maintained since I left Admitad GmbH. There was `new` branch (totally rewritten)
> https://github.com/admitad/admitad-php-api/tree/new/src
> Maybe it will be more suitable.
> 
> @bulychev check PR or ping smbd from team. Ask CTO who will maintain it. Or add notice in readme "NOT MAINTAINED"

ty

**Comment by bulychev** [comment]
You need use method authorizeClient for client_credentials grant type.

**Pull request closed without merging**
